version: '3.8'
services:
  db:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_DB: rpgwiki
      POSTGRES_USER: rpgwiki
      POSTGRES_PASSWORD: rpgwiki
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rpgwiki"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  pgdata:
